api:
  version: 1

spring:
  application:
    name: simple-storage-api
  lifecycle:
    timeout-per-shutdown-phase: 30s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html

management:
  server:
    port: ${MANAGEMENT_PORT:8081}
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /

server:
  adress: 0.0.0.0
  port: ${SERVER_PORT:8080}
  session:
    timeout: 120
  servlet:
    encoding:
      charset: UTF-8
      force: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  shutdown: graceful

fileio:
  url:
    base: ${FILE_IO_ENDPOINT_BASE:https://file.io}